apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo01-deployment
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: demo01-deployment
  template:
    metadata:
      labels:
        app: demo01-deployment
    spec:
      containers:
        - name: demo01-container
          image: sugnana/demo01:2.0.0
          ports:
            - containerPort: 8080